name: AccTest Command

on:
  issue_comment:
    types: [created]

jobs:
  acctest-command:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: echo "${{ github.event.issue_comment.sender.login }}"
        shell: bash
        run: echo "${{ github.event.issue_comment.sender.login }}"
      - name: echo ${{ github.event }}
        shell: bash
        run: echo ${{ github.event }}

      - uses: octokit/graphql-action@v2.x
        id: get_permission
        with:
          query: |
            query CollaboratorPermission($owner: String!, $repo: String!, $collaborator: String) {
              repository(owner:$owner, name:$repo) {
                collaborators(query: $collaborator) {
                  edges {
                    permission
                  }
                }
              }
            }
          owner: ${{ github.repository_owner }}
          collaborator: ${{ github.event.issue_comment.sender.login }}
          repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
      - run: "echo 'output: ${{ steps.get_permission.outputs.data }}'"

#       - name: Slash Command Dispatch
#         uses: peter-evans/slash-command-dispatch@v1.2.0
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           issue-type: pull-request
#           commands: acctest
#           named-args: true
#           permission: write
